### ISSUE TITLE
stm32F4discovery won't respond when adding too much mod sources?

### ISSUE THREAD

**Issue by ramonschepers** [JohannesTaelman/axoloti#11]
so, when i add more than 7 analog inputs (10k mono lin pots, all have different mod sources), and i went live on my board, the board hangs, and does not respond until i re-power it, the CPU usage is about 85% (with 7 analog inputs, running stable) so that's not a problem. update interval of each mod source is set to 103ms.
any ideas on this?

**Comment by JohannesTaelman** [comment]
Is patch->settings_.maximum number of modulations sources set to >7? This limit is not checked or enforced.
Some pins on the discovery are not free, check with the discovery user guide.

**Comment by ramonschepers** [comment]
oh whoops, i forgot to set the amount of modulation sources to be higher than 7, thanks for your help :)
