### ISSUE TITLE
git tag -> version

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#115]
Fetch the output of "git tag" in build.xml/pre-compile and insert that in the about box, and the manifest?

**Comment by TheTechnobear** [comment]
in progress

**Comment by TheTechnobear** [comment]
done note appears to be issue with javafx not accepting version numbers on app bundles !

http://stackoverflow.com/questions/27314448/how-to-change-the-version-number-on-a-bundle
