### ISSUE TITLE
mapping analog inputs directly without mod-sources

### ISSUE THREAD

**Issue by ramonschepers** [JohannesTaelman/axoloti#12]
feature request: ability to map more controls (example: slew rate) directly to an analog input to set your basic things.
i think it will be usefull for the newcomers in axoloti.

**Comment by JohannesTaelman** [comment]
Mapping similar to midi CC's? Parameter changes are supposed to be event-driven, generating continuous updates comes with a performance hit.
Or replacing a parameter with an inlet? The second option seems interesting to me, but requires a good user interface to make it non-confusing.

**Comment by ramonschepers** [comment]
i mean the second option :)

**Comment by JohannesTaelman** [comment]
Issue #93 describes it better, closing this one.
