### ISSUE TITLE
OBJ: missing objects (switch, tape delay, reverb, test signalgenerator) ... unstable objects in use

### ISSUE THREAD

**Issue by TheTechnobear** [JohannesTaelman/axoloti#140]
the following objects appear to be missing, either we create or delete demo/help etc (or adapt them)

switch/tape delay/reverb in : demos/youtube/guitar_multi_fx.axp

test signal generator , required for 3 tutorials:
15_waveshaper.axp, 21_modulated_delay1.axp, 22_overlap_add_shifter.axp

the following do not compile, due to 'unstable'  ? should we remove, and if so which objects?
fail to compile : /Users/kodiak/Projects/Music/axoloti/objects/unstable/spectral/vocoder 24.axh
fail to compile : /Users/kodiak/Projects/Music/axoloti/objects/wave/wave.axh

**Comment by JohannesTaelman** [comment]
working on this

**Comment by TheTechnobear** [comment]
added a test signal generator... but really only works for sine/noise/saw... not quite sure how the sample playback worked before. ... but at least compiles :)

**Comment by JohannesTaelman** [comment]
closing, samples relate to issue #105
