### ISSUE TITLE
Issues List: allow users to assign labels, have labels for axostudio,firmware,modules

### ISSUE THREAD

**Issue by TheTechnobear** [JohannesTaelman/axoloti#15]

**Comment by JohannesTaelman** [comment]
GitHub does not allow users to assign labels...

**Comment by TheTechnobear** [comment]
Sorry forgot to check this...

the deal is only collaborators can assign labels etc on public repos
(see
https://help.github.com/articles/what-are-the-different-access-permissions/)

but this will then given them read/write and pull access too, so perhaps a
bit too much at this stage. a bit of a 'blunt tool' for the time being.
