### ISSUE TITLE
GUI: general enhancements

### ISSUE THREAD

**Issue by TheTechnobear** [JohannesTaelman/axoloti#18]
i)  don't show about box on startup
ii) open recent patches... (list of 10 last opened patches)
iii) connected status in status bar?  (hmm need to consider multiple boards?)
iv) connected dialog, allow window to be closed... like a 'log window'?

**Comment by JohannesTaelman** [comment]
i) + ii) done
iii) + iv) need to be considered as part of the whole GUI approach: toolbars vs palettes vs docked windows
