### ISSUE TITLE
Patch: instance names must be C identifiers

### ISSUE THREAD

**Issue by TheTechnobear** [JohannesTaelman/axoloti#28]
looks like if you rename an object instance it must conform to C rules.
if you don't conform, it will disconnect all your connects next time you load the patch.
(a nasty here, is using spaces, as will be common by users)

probably unreasonable to expect musicians to know/follow this :) 

possible solutions:
i)  don't allow invalid characters 
ii) substitute invalid characters

I think users will accept that special characters cannot be used, so we can use (i) for this.
(we need to use an input mask to stop invalid character entries)

I think 'spaces' will probably be wanted, so perhaps we substitute these with underscore (_), 
(and underscore/space are the same), then we just need to do the substitution in the display.

**Comment by JohannesTaelman** [comment]
Just the space character was the problem, and fixed now. Object names have some character substitutions for C compliancy : axoloti.utils.CharEscape
