### ISSUE TITLE
Communication locks up when computer goes to sleep

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#36]

**Comment by TheTechnobear** [comment]
tested on Mac OS X with new build.... works fine

test: 
- Axoloti connected and with patch live.
- put mac to sleep (wait 30 seconds for to ensure in sleep)
- wake up mac

result:
on waking :  
- midi is available
- axoloti UI is shown disconnected  (as expected!)
- connect Axoloti UI (without unplugging) 
- can then take patch live again

so as far as mac is concerned, this can be closed.
