### ISSUE TITLE
copy of block of objects doesn't include connectors

### ISSUE THREAD

**Issue by timvets** [JohannesTaelman/axoloti#45]
linux (ubuntu), git pull at 21:52 UTC+01:00 today:
when making a copy of a block of connected objects,
the objects in the newly created copy aren't connected.
(some connections are there, others are not)

**Comment by JohannesTaelman** [comment]
ack, happens when there's a space character in the object instance name

**Comment by timvets** [comment]
you mean underscore? (there weren't any whitespaces in instance names)

**Comment by TheTechnobear** [comment]
simple test case

math/+1 to gain/vca (v)  wont restore connections

clipboard looks ok, so i guess its the restore...
seems to be some objects... e.g. vca I cant get it to restore any connections.
(I cant find a pattern of which objects have issues though, and which don't)


<patch>
   <obj type="math/+1" sha="61413e41a22dba4d3f6a4be145c06146934f7120" name="+1_1" x="210" y="336">
      <params/>
      <attribs/>
   </obj>
   <obj type="gain/vca" sha="6bbeaeb94e74091879965461ad0cb043f2e7f6cf" name="vca_1" x="322" y="336">
      <params/>
      <attribs/>
   </obj>
   <nets>
      <net>
         <source name="+1_1 result"/>
         <dest name="vca_1 v"/>
      </net>
   </nets>
   <notes><![CDATA[]]></notes>
</patch>

**Comment by TheTechnobear** [comment]
got it... its with inlets/outlets with 1 char names.. will check in a fix now
