### ISSUE TITLE
Axoloti main window jumps on top when setting patch live

### ISSUE THREAD

**Issue by timvets** [JohannesTaelman/axoloti#51]
In Linux, when going into live mode, the Axoloti main window jumps on top.
This does not happen when running as "sudo ./Axoloti.sh" (which was the only way before adapting 49-axoloti.rules)

**Comment by JohannesTaelman** [comment]
Is bug recently introduced?
Main window jumping to top is supposed to be triggered by severe errors (in red) - like a compile fail. That's where you'll find the compiler error anyway.

**Comment by timvets** [comment]
indeed there is some red in the main window:

null
Generate code complete

are the first two lines after going into live mode. 'null' in red
It nevertheless successfully runs the patch.

**Comment by timvets** [comment]
no 'null' when running as root.

**Comment by JohannesTaelman** [comment]
So it's a matter of finding the origin of the "null" error. Do you get an exception in the terminal (from where you launched Axoloti.sh)?

**Comment by timvets** [comment]
hmm, maybe still some permission problem:
SEVERE: null
java.io.FileNotFoundException: patch/xpatch.cpp (Permission denied)

**Comment by JohannesTaelman** [comment]
You need to transfer file ownership of the whole tree to your user. Running axoloti as superuser created files your user does not have permissions for.

**Comment by timvets** [comment]
ah, the reason was because I've been running Axoloti.sh as root before.
removed patch/xpatch.cpp, which was owned by root, and now it can create a new xpatch.cpp owned by user.
