### ISSUE TITLE
Board selection

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#54]
Replacing the serial port selection dialog...

**Comment by TheTechnobear** [comment]
is this going to allow multiple board connection via USB connections .... or not quite yet :)

**Comment by JohannesTaelman** [comment]
different options for multiple board connections.
libusb could tell which port it is attached to
or the cpuid could be exposed in the usb descriptor
2nd would be preferred but that makes the usb descriptor a dynamic string
either way is going to be a bit cryptic

Not very high priority. Removing visible references to serial port is more urgent.

**Comment by TheTechnobear** [comment]
Yeah 2nd is preferable if you want different boards for specific purposes (
quite likely)
What about defaulting to cpuid but allowing it to be renamed and saved in
firmware?
( hmm, seems similar to board settings we were discussing re: input gain
etc)

Btw it might good idea if your refactoring to consider board selection will
at some point be required at patch window level ... So you can have
multiple boards connected and running patches.
( again not for now feature, but perhaps worth hating in mind )

Don't think many of us order multiple boards :) but hopefully that could
change once everyone is blown overboard by axoloti

**Comment by JohannesTaelman** [comment]
ack
