### ISSUE TITLE
OBJ: patch/patcher object: gui not refreshing

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#61]

**Comment by TheTechnobear** [comment]
more details?

**Comment by JohannesTaelman** [comment]
steps to reproduce:
1. create a "patch/patcher" object
2. press the "edit" button of that object
3. add an inlet object to that patch
4. go back to the parent patch
5. press the "update" button of the "patch/patcher" object
The space for the inlet appears, but the inlet is not drawn until the object is fully redrawn by moving it for instance.

**Comment by TheTechnobear** [comment]
fixed, and pushed
