### ISSUE TITLE
GUI: "rendering" problem, preset area

### ISSUE THREAD

**Issue by ElectronicBattle** [JohannesTaelman/axoloti#7]
The toolbar area which says "preset recall edit i 1 2 3 4 5 6 7 8" top right hand side of patcher environment ... the "button" for the both number eights isn't fully rendered on the right hand half of the button. The button still "clicks" but you can't read it.

Linux Mint 17.1, java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
1680x1050, dual monitors using Nvidia 331.113
see screenshot (hopefully attached):
![screenshot](https://cloud.githubusercontent.com/assets/10836275/6027813/7a9ccc4e-abdc-11e4-9f49-6928f944f15e.png)

**Comment by JohannesTaelman** [comment]
Screenshot is clear, thanks.
The whole preset GUI needs revision. The number of presets is not limited to 8 but a patch setting, while the GUI does not reflect this.
