### ISSUE TITLE
OBJ: env/d m parameter scaling

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#71]

**Comment by TheTechnobear** [comment]
details? example patch?

**Comment by JohannesTaelman** [comment]
"env/d lin" 
"env/d m"
"env/ahd lin"
"env/ahd lin"
"env/ahd lin"
"env/hd"
"env/hd m"
"env/hd lin"
"env/line 2"
"env/line 2 bp"
"env/line 3"
"env/line 3 bp"
have unacceptable parameter scaling, with infinity at zero.
The "x" suffix variations fixed that but never got to remove the non-"x" variations.
